const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const scriptPath = path.join(__dirname, '..', 'GloryApiTray.ps1')
const modulePath = path.join(__dirname, '..', 'GloryApiTray.Core.psm1')
const script = fs.readFileSync(scriptPath, 'utf8')
const moduleText = fs.readFileSync(modulePath, 'utf8')

test('tray control stays loopback and exposes revisioned routing actions', () => {
  assert.match(script, /GloryApiTray\.Core\.psm1/)
  assert.match(moduleText, /function Assert-LocalHttpUrl/)
  assert.match(script, /127\.0\.0\.1:3101/)
  assert.match(script, /Get-Json '\/api\/control\/status'/)
  assert.match(moduleText, /DnsSafeHost\.Trim\('\[', '\]'\)/)
  assert.doesNotMatch(moduleText, /'localhost'/i)
  assert.match(moduleText, /function Save-GloryControlOrder/)
  assert.match(moduleText, /expectedRevision\s*=/)
  assert.match(script, /Show-ControlWindow/)
  assert.match(script, /Toggle-SelectedModel/)
  assert.match(script, /Move-SelectedModel/)
  assert.doesNotMatch(script, /config\.toml|CODEX_HOME/i)
  assert.doesNotMatch(script, /Start-Process[^\r\n]*freellmapi/i)
})
