# Prepara un perfil Codex temporal para el canary de GloryAPI.
# No modifica config.toml ni selecciona el perfil; la activación es explícita con
# `codex --profile gloryapi-canary` o desde el selector equivalente del cliente.
[CmdletBinding()]
param(
    [switch]$Force,
    [ValidateRange(1024, 65535)]
    [int]$BridgePort = 4100
)

$ErrorActionPreference = 'Stop'
$codexHome = if ($env:CODEX_HOME) { $env:CODEX_HOME } else { Join-Path $env:USERPROFILE '.codex' }
$profileName = 'gloryapi-canary'
$profilePath = Join-Path $codexHome "$profileName.config.toml"
$authScript = (Resolve-Path (Join-Path $PSScriptRoot 'get-codex-auth.ps1')).Path

if (-not (Test-Path -LiteralPath $codexHome)) {
    New-Item -ItemType Directory -Path $codexHome -Force | Out-Null
}
if ((Test-Path -LiteralPath $profilePath) -and -not $Force) {
    throw "El perfil ya existe: $profilePath. Usa -Force solo para reemplazar este perfil temporal."
}

function Convert-ToTomlString([string]$value) {
    return '"' + ($value -replace '\\', '\\' -replace '"', '\"') + '"'
}

$authCommand = Convert-ToTomlString 'powershell.exe'
$authArgs = @(
    '-NoLogo',
    '-NoProfile',
    '-NonInteractive',
    '-ExecutionPolicy',
    'Bypass',
    '-File',
    $authScript
) | ForEach-Object { Convert-ToTomlString $_ }

$content = @"
# Generated by GloryAPI prepare-canary-profile.ps1; safe to delete.
# This is a temporary profile and does not replace config.toml.
model = "auto"
model_provider = "$profileName"
model_reasoning_effort = "high"
model_catalog_json = "C:/Users/Owner/.codex/models.json"

[model_providers.$profileName]
name = "GloryAPI Canary (local sidecar)"
base_url = "http://127.0.0.1:$BridgePort/v1"
wire_api = "responses"
supports_websockets = false
requires_openai_auth = false
request_max_retries = 0
stream_max_retries = 0
stream_idle_timeout_ms = 300000

[model_providers.$profileName.auth]
command = $authCommand
args = [$($authArgs -join ', ')]
timeout_ms = 5000
refresh_interval_ms = 300000
"@

$temporary = "$profilePath.tmp.$PID"
try {
    [System.IO.File]::WriteAllText($temporary, $content, [System.Text.UTF8Encoding]::new($false))
    Move-Item -LiteralPath $temporary -Destination $profilePath -Force
} finally {
    if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary -Force }
}

Write-Host "Perfil canary creado: $profilePath"
Write-Host "No se modificó config.toml. Actívalo explícitamente con: codex --profile $profileName"
Write-Host "Rollback: detener el bridge y volver al perfil ChatGPT activo."
