# Prepara un CODEX_HOME independiente para la sesión Codex que usa GloryAPI.
# Solo copia configuración; nunca copia auth.json ni bases/historial del home normal.
[CmdletBinding()]
param(
    [string]$BridgeHome = (Join-Path $env:USERPROFILE '.codex-gloryapi'),
    [string]$SourceCodexHome = (Join-Path $env:USERPROFILE '.codex'),
    [ValidatePattern('^[A-Za-z0-9_-]+$')]
    [string]$ProfileName = 'gloryapi-bridge',
    [ValidateRange(1024, 65535)]
    [int]$BridgePort = 4100,
    [switch]$RefreshConfig
)

$ErrorActionPreference = 'Stop'

function Resolve-FullPath([string]$PathValue) {
    return [IO.Path]::GetFullPath($PathValue).TrimEnd('\')
}

function Convert-ToTomlString([string]$Value) {
    return '"' + ($Value -replace '\\', '\\' -replace '"', '\"') + '"'
}

function Write-AtomicText([string]$PathValue, [string]$Content) {
    $temporary = "$PathValue.tmp.$PID"
    try {
        [IO.File]::WriteAllText($temporary, $Content, [Text.UTF8Encoding]::new($false))
        Move-Item -LiteralPath $temporary -Destination $PathValue -Force
    }
    finally {
        if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary -Force }
    }
}

$SourceCodexHome = Resolve-FullPath $SourceCodexHome
$BridgeHome = Resolve-FullPath $BridgeHome
if ($SourceCodexHome.Equals($BridgeHome, [StringComparison]::OrdinalIgnoreCase)) {
    throw 'El CODEX_HOME aislado debe ser diferente del CODEX_HOME normal.'
}

$sourceConfig = Join-Path $SourceCodexHome 'config.toml'
$bridgeConfig = Join-Path $BridgeHome 'config.toml'
$profilePath = Join-Path $BridgeHome "$ProfileName.config.toml"
$authScript = Resolve-FullPath (Join-Path $PSScriptRoot 'get-codex-auth.ps1')
$modelsPath = Join-Path $SourceCodexHome 'models.json'

if (-not (Test-Path -LiteralPath $sourceConfig -PathType Leaf)) {
    throw "No existe la configuración normal de Codex: $sourceConfig"
}
if (-not (Test-Path -LiteralPath $BridgeHome -PathType Container)) {
    New-Item -ItemType Directory -Path $BridgeHome -Force | Out-Null
}

# La configuración base conserva plugins, MCP y preferencias no relacionadas
# con el proveedor. Se copia únicamente config.toml, nunca el estado del home.
if ($RefreshConfig -or -not (Test-Path -LiteralPath $bridgeConfig -PathType Leaf)) {
    Copy-Item -LiteralPath $sourceConfig -Destination $bridgeConfig -Force
}

$authArgs = @(
    '-NoLogo',
    '-NoProfile',
    '-NonInteractive',
    '-ExecutionPolicy',
    'Bypass',
    '-File',
    $authScript
) | ForEach-Object { Convert-ToTomlString $_ }

$catalogLine = if (Test-Path -LiteralPath $modelsPath -PathType Leaf) {
    "model_catalog_json = $(Convert-ToTomlString (Resolve-FullPath $modelsPath))"
} else {
    ''
}

$trustedPaths = "$(Resolve-FullPath $BridgeHome);$(Resolve-FullPath $SourceCodexHome)"
$content = @"
# Generated by prepare-isolated-home.ps1.
# This profile has its own CODEX_HOME, state database and conversation history.
model = "deepseek-v4-flash"
model_provider = "$ProfileName"
model_reasoning_effort = "high"
$catalogLine
log_dir = $(Convert-ToTomlString (Join-Path $BridgeHome 'log'))
notify = []

[model_providers.$ProfileName]
name = "GloryAPI Bridge (isolated)"
base_url = "http://127.0.0.1:$BridgePort/v1"
wire_api = "responses"
supports_websockets = false
requires_openai_auth = false
request_max_retries = 0
stream_max_retries = 0
stream_idle_timeout_ms = 300000

[model_providers.$ProfileName.auth]
command = "powershell.exe"
args = [$($authArgs -join ', ')]
timeout_ms = 5000
refresh_interval_ms = 300000

[features]
js_repl = true

[mcp_servers.node_repl.env]
CODEX_HOME = $(Convert-ToTomlString $BridgeHome)
NODE_REPL_TRUSTED_CODE_PATHS = $(Convert-ToTomlString $trustedPaths)

[history]
persistence = "save"
"@

Write-AtomicText $profilePath $content
Write-Host "CODEX_HOME aislado listo: $BridgeHome"
Write-Host "Perfil: $profilePath"
Write-Host 'No se copiaron conversaciones, auth.json ni bases SQLite del home normal.'
